### model
model_name_or_path: /processing_data/infra/lvjiahui/8b/dpo
reward_model: /processing_data/infra/lvjiahui/8b/rm
reward_model_type: full
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: /processing_data/infra/lvjiahui/study/LLM/RLHF/ds_config/ds_z2_config.json

### dataset
dataset: ppo
template: llama3
flash_attn: fa2
dataset_dir: /processing_data/infra/lvjiahui/LLaMA-Factory/data
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /processing_data/infra/lvjiahui/8b/ppo
logging_steps: 5
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: none

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
